@startuml Combat_System Strategy + Observer

class Player{
    - name: String
    - HP: int
    - inventory: List<Item>
}

class Enemy{
    - name: String
    - HP: int
}

interface ActionStrategy{
    + execute(user: Character, target: Character)
}

class AttackAction implements ActionStrategy{
    - combatStrategy: CombatCalculationStrategy
    + execute(user,target0)
}

class ItemAction implements ActionStrategy{
    - item: Item
    + execute(user, target)
}

Player --> ActionStrategy : user
Enemy-->ActionStrategy : target
@enduml