@startuml MVC
title MVC Architecture for RPG Game

package "Model" {

    interface ActionStrategy{
    }

    class AttackAction{
    }

    class ItemAction{
    }

    class Stats {
    }

    class ItemStats {
    }

    class GameState {
    }
    class GameStateMemento{}

    class CharacterPG {
    }

    class Player{
    }
    class Enemy{

    }

    class Job {
    }

    class Inventory {
    }

    class Item {
    }

    class NPC {
    }
    class MovesNPC

    class WorldPosition {
    }

    class Position{}
    class Party {
    }

    class Battle {
    }

    

    interface TurnStrategy {
    }

    class StaticSpeedTurn {
    }

    class Ability {
    }

    interface TurnIterator {
    }

    class ConcreteTurnIterator {
    }

    interface RewardStrategy {
    
    }

    class StandardRewardStrategy{
    }

    class NoRewardStrategy {
    }

    class Reward {
    }
}

package "Controller" {

    class MainMenuController {
       
    }

    class GameController {
    }

    class MovementController {
    }

    class BattleController {
    }

    abstract class GameViewCreator {
    }

    class NewGameViewCreator {
    }

    class ContinueGameViewCreator {
    }
    
    class ExplorationController{}
    class MapBuilder{}
    class SaveManager{}
    class ViewManager{}

}

package "View" {

    class MainMenuView {
    }

    class SaveMenuView {
    }

    class DialogueView {
    }

    class BattleView {
    }

    class ExplorationView {
    }

    abstract class GameView {
    }

    class NewGameView {
    }

    class ContinueGameView {
    }

    class HUD
    class ShopView
}
@enduml