@startuml US18
title Character Evolution


'Interfaccia Strategy'
interface ActionStrategy{
    + execute(user: Character, target: Character)
}
enum MoveType{
    +createMove(move:Move): ActionStrategy
}
class Player{
    - currentMoves: List<Move>
    +learnMove(m: Move)
}
class MovesNPC extends NPC{
    +interact(player: Player): void
}

Playero--Ability: apply()
MoveType..>Ability: creates
@enduml