@startuml
title Choose character job
'Abstract Factory'
abstract class Character{
    - job: Job
    -baseStats: Stats
    -currentStats: Stats
    -position: Position
    +createCharacterSprite(): ImageView
    +takeDamage(int value): void
    +heal(int value): void
}

class Player extends Character{
    - xp: int
    - follower: Player
    - imgSprite: Image
    +notifyFollower(): void
    +subscribeToFollowed(): void
    +unsubscribeFromFollowed(): void
    +addXp(): void
    +takeDamage(int value): void
    +heal(int value): void
}
class Enemy extends Character{
    - imgSprite: Image
    +addXp(): void
    +takeDamage(int value): void
    +heal(int value): void
}

@enduml