@startuml Combat_System Strategy + Observer

class Player{
    - name: String
    - HP: int
    - inventory: List<Item>
}

class Enemy{
    - name: String
    - HP: int
}

interface ActionStrategy{
    + execute(user: Character, target: Character)
}

abstract class MoveAction implements ActionStrategy{
    - move: Move
    - combatStrategy: CombatCalculationStrategy
    + execute(user,target)
}

abstract class OffensiveMove extends MoveAction {
    - move: Move
    + execute(user,target)
    + calculateDamage(user,target)
}

class AttackMove extends OffensiveMove {
    - move: Move
    + execute(user,target)
    + calculateDamage(user,target)
}

class HealMove extends MoveAction {
    - move: Move
    + execute(user,target)
}

class MagicAttackMove extends OffensiveMove {
    - move: Move
    + execute(user,target)
    + calculateDamage(user,target)
}

class ItemAction implements ActionStrategy{
    - item: Item
    + execute(user, target)
}

Player --> ActionStrategy : user
Enemy-->ActionStrategy : target
@enduml