@startuml GameLauncher

title GameLauncher

class App{
    + main(): void
}
App-->GameLauncher: calls getIstance()

class GameLauncher{
    - static instance : GameLauncher
    - GameLauncher()
    +static getIstance(): GameLauncher
    + launch() : void
}

class MainMenu{
    +show() : void
}

GameLauncher-->MainMenu: launch

abstract class GameCreator{
    + createGame(): Game
}

class NewGameCreator{
    + createGame(): Game
}

class ContinueGameCreator{
    + createGame(): Game
}

GameCreator -down-> NewGameCreator
GameCreator -down-> ContinueGameCreator
GameCreator --> Game : create

abstract class Game{
    - GameState: gameState
}

class NewGame{}
class ContinueGame{}

class NewGame {}
class ContinueGame {}

Game <|-- NewGame
Game <|-- ContinueGame

class NewGameView {
    + render(): void
}
class SaveMenuView {
    + render(): void
}

NewGame --> NewGameView
ContinueGameCreator --> SaveMenuView

' ===== Singleton GameInstance =====
class GameInstance {
    - static instance: GameInstance
    - gameCreator: GameCreator
    + getInstance(): GameInstance
}

GameInstance --> GameCreator
GameInstance --> GameInstance

class MainMenuController{
    + handleSelection(option: String): void
}

MainMenu --> MainMenuController : user input
MainMenuController --> GameCreator : createGame()
MainMenuController --> GameView : render()

'Choose character job, uso Abstract Factory'
abstract class Character{
    -abilities: List<Ability>
    - job: Job
    -baseStats: Stats
    -currentStats: Stats
    -position: Position
    -inCombat: boolean
    +refreshCurrentStats(): void
    +enterCombat(): void
    +exitCombat(): void
    +isInCombat(): boolean
    +createCharacterSprite(): ImageView
    +useAbilities(): void
    +addAbility(a: Ability): void
    +getAbilities(): List<Ability>
    +takeDamage(int value): void
    +heal(int value): void
}

class Player extends Character{
    - xp: int
    - follower: Player
    - imgSprite: Image
    - abilities: List<Ability>
    +notifyFollower(): void
    +subscribeToFollowed(): void
    +unsubscribeFromFollowed(): void
    +addXp(): void
    +takeDamage(int value): void
    +heal(int value): void
    +addAbility(a: Ability): void
    +getAbilities(): List<Ability>
    +useAbilities(): void
    +hasAbility(): boolean
}
class Enemy extends Character{
    - imgSprite: Image
    +takeDamage(int value): void
    +heal(int value): void
}

class CharacterSelectionView{
    +show(): void
    +createCard(Job job): void
    +selectCharacter(Job job,VBox card): void
}
class GameController{
    +onNewGameConfirmed(int players,boolean autoSave): void
    +goToCharacterSelection(): void
    +onCharacterSelected(Job job): void
    +createParty(): void
    +createEnemy():  void
    +createNPC(): void

}
enum Job{}
CharacterSelectionView-->GameController: user selects job
NewGameView-->CharacterSelectionView: selectJobs()
GameController-->Player:createParty()
GameController-->Enemy:createEnemy()
Player-->Job
Enemy-->Job

'Character Evolution, Strategy'
interface Ability{
    +getName(): String
    +getDescription(): String
    +getCost(): int
    +apply(player: Player): void
}

class FireballAbility implements Ability{
    +getName(): String
    +getDescription(): String
    +getCost(): int
    +apply(player: Player): void
}

class HealAbility implements Ability{
    +getName(): String
    +getDescription(): String
    +getCost(): int
    +apply(player: Player): void
}

Player->Ability: apply()

'Builder'

class MapBuilder{
    - MapView map
    + addLayer(layer)
    + build()
}

  class ExplorationView {
    + renderMap()
  }

  class ExplorationController {
    + movePlayer(direction)
    + updatePartyFollow()
  }

  ExplorationView --> ExplorationController
  ExplorationView --> MapBuilder

  CharacterSelectionView-->ExplorationView: startExploration()
@enduml